import { StyleSheet } from 'react-native';
import { useThemeColors } from '../store/preferencesStore';

type ThemeColors = ReturnType<typeof useThemeColors>;

/**
 * Factory de estilos para la pantalla Home,
 * dependiente del tema actual.
 */
export const createHomeStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    screen: {
      backgroundColor: colors.backgroundMain,
      flex: 1,
    },
    contentContainer: {
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 32,
    },

    // Header usuario
    headerCard: {
      backgroundColor: colors.backgroundCard,
      borderRadius: 24,
      paddingVertical: 32,
      paddingHorizontal: 24,
      marginBottom: 18,
      shadowColor: '#000',
      shadowOpacity: 0.15,
      shadowOffset: { width: 0, height: 8 },
      shadowRadius: 16,
      elevation: 8,
      borderWidth: 0.5,
      borderColor: colors.primaryButton,
    },
    headerMain: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 18,
    },
    avatarSmall: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: colors.primaryButton,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: colors.primaryButton,
      shadowOpacity: 0.4,
      shadowOffset: { width: 0, height: 6 },
      shadowRadius: 12,
      elevation: 8,
      flexShrink: 0,
    },
    avatarSmallText: {
      fontSize: 32,
      fontWeight: '900',
      color: '#ffffff',
    },
    avatarSmallImage: {
      width: 76,
      height: 76,
      borderRadius: 38,
    },
    headerInfo: {
      flex: 1,
      justifyContent: 'center',
    },
    greetingSmall: {
      fontSize: 12,
      color: colors.grayPlaceholder,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.6,
      marginBottom: 8,
    },
    userNameSmall: {
      fontSize: 22,
      fontWeight: '900',
      color: colors.textTitle,
      letterSpacing: 0.3,
      marginBottom: 14,
    },
    headerBottom: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    rolePill: {
      paddingVertical: 10,
      paddingHorizontal: 13,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      gap: 7,
      flexDirection: 'row',
      shadowColor: colors.primaryButton,
      shadowOpacity: 0.25,
      shadowOffset: { width: 0, height: 3 },
      shadowRadius: 6,
      elevation: 3,
      backgroundColor: colors.primaryButton,
    },
    rolePillText: {
      fontSize: 12,
      fontWeight: '900',
      color: '#ffffff',
      letterSpacing: 0.4,
    },
    pedidosBadge: {
      paddingVertical: 10,
      paddingHorizontal: 10,
      borderRadius: 12,
      backgroundColor: 'transparent',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      borderWidth: 1.5,
      borderColor: colors.primaryButton,
    },
    pedidosText: {
      fontSize: 12,
      fontWeight: '800',
      color: colors.primaryButton,
      letterSpacing: 0.3,
    },

    // Hero alquiler
    heroContainer: {
      backgroundColor: colors.backgroundCard,
      borderRadius: 24,
      paddingVertical: 24,
      paddingHorizontal: 20,
      marginBottom: 24,
      shadowColor: '#000',
      shadowOpacity: 0.12,
      shadowOffset: { width: 0, height: 6 },
      shadowRadius: 12,
      elevation: 6,
      borderWidth: 0.5,
      borderColor: colors.borderMain,
    },
    heroBadgeRow: {
      flexDirection: 'row',
      justifyContent: 'flex-start',
      marginBottom: 10,
    },
    heroBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingVertical: 4,
      paddingHorizontal: 10,
      borderRadius: 999,
      backgroundColor: colors.backgroundMain,
      borderWidth: 1,
      borderColor: colors.borderMain,
    },
    heroBadgeText: {
      fontSize: 11,
      fontWeight: '600',
      color: colors.textBody,
    },
    heroTitle: {
      fontSize: 22,
      fontWeight: '900',
      color: colors.textTitle,
      letterSpacing: 0.3,
      marginBottom: 6,
    },
    heroHighlightsRow: {
      flexDirection: 'row',
      gap: 12,
      marginBottom: 16,
    },
    heroHighlight: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
      paddingVertical: 10,
      paddingHorizontal: 10,
      borderRadius: 14,
      backgroundColor: colors.backgroundMain,
    },
    heroHighlightTextWrap: {
      flex: 1,
    },
    heroHighlightTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.textTitle,
      marginBottom: 2,
    },
    heroHighlightSubtitle: {
      fontSize: 11,
      color: colors.textBody,
    },
    heroActionsRow: {
      flexDirection: 'column',
      alignItems: 'stretch',
      gap: 10,
      marginTop: 4,
    },
    heroPrimaryButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingVertical: 11,
      borderRadius: 14,
      backgroundColor: colors.primaryButton,
    },
    heroPrimaryButtonText: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.backgroundMain,
    },
    heroSecondaryButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 14,
      backgroundColor: colors.backgroundMain,
      borderWidth: 1,
      borderColor: colors.borderMain,
    },
    heroSecondaryButtonText: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.primaryButton,
    },

    // Sección motos / favoritos
    section: {
      marginBottom: 24,
    },
    sectionTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.grayPlaceholder,
      marginBottom: 12,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    favoritesButton: {
      backgroundColor: colors.backgroundCard,
      borderRadius: 16,
      paddingVertical: 14,
      paddingHorizontal: 16,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
      borderWidth: 1,
      borderColor: colors.borderMain,
    },
    favoritesIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.primaryButton,
      justifyContent: 'center',
      alignItems: 'center',
    },
    favoritesTextWrap: {
      flex: 1,
    },
    favoritesTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textTitle,
      marginBottom: 2,
    },
    favoritesSubtitle: {
      fontSize: 12,
      color: colors.textBody,
    },
  });