import { StyleSheet } from "react-native";
import { useThemeColors } from "../store/preferencesStore";

type ThemeColors = ReturnType<typeof useThemeColors>;

export const createReservasStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.backgroundMain,
      padding: 16,
    },
    center: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: colors.backgroundMain,
    },
    helper: {
      marginTop: 12,
      color: colors.grayLabelText,
    },
    card: {
      backgroundColor: colors.backgroundCard,
      borderRadius: 14,
      padding: 14,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.borderMain,
    },
    cardCanceled: {
      opacity: 0.5,
    },
    header: {
      backgroundColor: colors.backgroundCard,
      borderRadius: 14,
      padding: 14,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.borderMain,
    },
    headerRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 6,
    },
    headerTitle: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.textTitle,
    },
    headerSubtitle: {
      marginTop: 4,
      fontSize: 12,
      color: colors.grayLabelText,
    },
    headerHelper: {
      marginTop: 4,
      fontSize: 11,
      color: colors.grayPlaceholder,
    },
    headerIconBadge: {
      width: 34,
      height: 34,
      borderRadius: 17,
      borderWidth: 1,
      borderColor: colors.borderMain,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.tabBackground,
    },
    cardHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
      marginBottom: 6,
    },
    codeRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    code: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.textTitle,
    },
    dateRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 8,
      gap: 12,
    },
    dateItem: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    dateSeparator: {
      width: 1,
      height: 18,
      backgroundColor: colors.borderMain,
      opacity: 0.4,
    },
    modelRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginTop: 4,
    },
    modelText: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textBody,
    },
    metaLabel: {
      fontSize: 11,
      color: colors.grayLabelText,
      textTransform: "uppercase",
    },
    metaValue: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textBody,
    },
    priceRow: {
      marginTop: 6,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    priceText: {
      fontSize: 12,
      color: colors.textBody,
    },
    totalText: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.textTitle,
    },
    statusPill: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
      backgroundColor: colors.tabBackground,
      borderWidth: 1,
      borderColor: colors.borderMain,
    },
    statusText: {
      fontSize: 11,
      fontWeight: "700",
      color: colors.textBody,
    },
    statusPrepared: {
      backgroundColor: "rgba(59, 130, 246, 0.15)",
      borderColor: "#3B82F6",
    },
    statusDelivered: {
      backgroundColor: "rgba(16, 185, 129, 0.15)",
      borderColor: "#10B981",
    },
    statusReturned: {
      backgroundColor: "rgba(37, 99, 235, 0.12)",
      borderColor: "#2563EB",
    },
    statusReview: {
      backgroundColor: "rgba(245, 158, 11, 0.15)",
      borderColor: "#F59E0B",
    },
    statusFinished: {
      backgroundColor: "rgba(22, 163, 74, 0.18)",
      borderColor: "#16A34A",
    },
    actionsRow: {
      marginTop: 12,
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 8,
    },
    cancelButton: {
      width: 34,
      height: 34,
      borderRadius: 17,
      borderWidth: 0,
      backgroundColor: "#EF4444",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.12,
      shadowRadius: 4,
      elevation: 2,
      alignItems: "center",
      justifyContent: "center",
    },
    cancelButtonText: {
      fontSize: 12,
      fontWeight: "700",
      color: "#ffffff",
    },
    editButton: {
      width: 34,
      height: 34,
      borderRadius: 17,
      borderWidth: 0,
      backgroundColor: colors.primaryButton,
      shadowColor: colors.primaryButton,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.16,
      shadowRadius: 4,
      elevation: 2,
      alignItems: "center",
      justifyContent: "center",
    },
    editButtonText: {
      fontSize: 12,
      fontWeight: "700",
      color: "#ffffff",
    },
    statusCancel: {
      backgroundColor: "rgba(239, 68, 68, 0.15)",
      borderColor: "#EF4444",
    },
    emptyContainer: {
      flexGrow: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    emptyWrapper: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 40,
      gap: 8,
    },
    emptyTitle: {
      fontSize: 15,
      fontWeight: "600",
      color: colors.textTitle,
    },
    emptyText: {
      color: colors.grayPlaceholder,
      fontSize: 13,
      textAlign: "center",
      paddingHorizontal: 24,
    },
    notesBox: {
      marginTop: 8,
      padding: 8,
      borderRadius: 8,
      backgroundColor: colors.backgroundMain,
      borderWidth: 1,
      borderColor: colors.borderMain,
    },
    notesLabel: {
      fontSize: 11,
      fontWeight: "700",
      color: colors.grayLabelText,
      marginBottom: 2,
    },
    notesText: {
      fontSize: 12,
      color: colors.textBody,
    },
    modalBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "rgba(0,0,0,0.4)",
    },
    modalContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    modalCard: {
      width: "90%",
      maxWidth: 420,
      backgroundColor: colors.backgroundCard,
      borderRadius: 16,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.borderMain,
    },
    modalHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 12,
    },
    modalTitle: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.textTitle,
    },
    modalAction: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.primaryButton,
    },
    modalRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      gap: 8,
      marginBottom: 12,
    },
    modalDateButton: {
      flex: 1,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
      backgroundColor: colors.inputBackground,
    },
    modalDateLabel: {
      fontSize: 11,
      color: colors.grayLabelText,
      textTransform: "uppercase",
    },
    modalDateValue: {
      marginTop: 4,
      fontSize: 13,
      color: colors.textBody,
      fontWeight: "600",
    },
    pickerWrapper: {
      borderWidth: 1,
      borderColor: colors.borderMain,
      borderRadius: 10,
      padding: 6,
      marginBottom: 12,
      backgroundColor: colors.backgroundMain,
    },
    modalActionsRow: {
      marginTop: 4,
      flexDirection: "row",
      justifyContent: "flex-end",
    },
    saveEditButton: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 10,
      backgroundColor: colors.primaryButton,
    },
    saveEditButtonDisabled: {
      opacity: 0.7,
    },
    saveEditButtonText: {
      fontSize: 13,
      fontWeight: "700",
      color: "#fff",
    },
  });
